version: 0.2

# AWS CodeBuild buildspec para CI/CD Pipeline
# Este archivo define las fases de construcción para integración continua y despliegue continuo
# Incluye: Tests unitarios, Build de imagen Docker, Push a ECR, y generación de artefactos para CodeDeploy
# Última actualización: 2025-11-10 - Servicio ECS recreado con rol correcto

phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 18
    commands:
      - echo "=== FASE INSTALL ==="
      - echo "Instalando dependencias de Python..."
      - python --version
      - pip --version
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "✅ Dependencias de Python instaladas"
      - echo ""
      - echo "Instalando Newman para tests de API..."
      - node --version
      - npm --version
      - npm install -g newman newman-reporter-htmlextra
      - newman --version
      - echo "✅ Newman instalado correctamente"

  pre_build:
    commands:
      - echo "=== FASE PRE_BUILD ==="
      - echo "Ejecutando pruebas unitarias..."
      - echo "Configuracion de entorno de testing..."
      - export FLASK_ENV=testing
      - export DATABASE_URL="sqlite:///:memory:"
      - export JWT_SECRET_KEY=test-secret-key
      - export STATIC_JWT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3RhdGljLXVzZXIiLCJyb2xlIjoiYWRtaW4ifQ.6bUHdYJk1cRnn-SVZEXAMPLEpR0fZ2mJb_YWbl8pW1lM
      - echo "Ejecutando tests con pytest..."
      - pytest tests/ -v --tb=short
      - echo "Generando reporte de cobertura..."
      - coverage run -m pytest tests/
      - coverage report
      - coverage html
      - echo "✅ Todas las pruebas pasaron exitosamente"
      - echo ""
      - echo "=== PREPARANDO DOCKER BUILD ==="
      - echo "Autenticándose en Amazon ECR..."
      - aws --version
      - echo "Obteniendo región de AWS..."
      - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "AWS Account ID - $AWS_ACCOUNT_ID"
      - echo "AWS Region - $AWS_DEFAULT_REGION"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "✅ Autenticación exitosa en ECR"
      - echo ""
      - echo "Configurando variables de imagen Docker..."
      - export IMAGE_REPO_NAME=${IMAGE_REPO_NAME:-popcorn-blacklist-api}
      - export IMAGE_TAG=${IMAGE_TAG:-latest}
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo "Repository URI - $REPOSITORY_URI"
      - echo "Image Tag - $IMAGE_TAG"

  build:
    commands:
      - echo "=== FASE BUILD ==="
      - echo "Construyendo imagen Docker para linux/amd64 (AWS Fargate)..."
      - docker build --platform linux/amd64 -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo "✅ Imagen Docker construida exitosamente"
      - echo ""
      - echo "Etiquetando imagen para ECR..."
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "✅ Imagen etiquetada"
      - echo ""
      - echo "Listando imágenes Docker locales..."
      - docker images

  post_build:
    commands:
      - echo "=== FASE POST_BUILD ==="
      - echo "Subiendo imagen a Amazon ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "✅ Imagen subida exitosamente a ECR"
      - echo ""
      - echo "Generando imagedefinitions.json para CodeDeploy ECS..."
      - printf '[{"name":"popcorn-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "✅ imagedefinitions.json creado"
      - cat imagedefinitions.json
      - echo ""
      - echo "Generando imageDetail.json para el pipeline..."
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - echo "✅ imageDetail.json creado"
      - cat imageDetail.json
      - echo ""
      - echo "Actualizando taskdef.json con la nueva imagen..."
      - sed -i "s|<IMAGE1_NAME>|$REPOSITORY_URI:$IMAGE_TAG|g" taskdef.json
      - sed -i "s|<AWS_ACCOUNT_ID>|$AWS_ACCOUNT_ID|g" taskdef.json
      - echo "✅ taskdef.json actualizado"
      - cat taskdef.json
      - echo ""
      - echo "=== RESUMEN DEL BUILD ==="
      - echo "✅ Tests ejecutados correctamente"
      - echo "✅ Cobertura generada"
      - echo "✅ Imagen Docker construida - $REPOSITORY_URI:$IMAGE_TAG"
      - echo "✅ Imagen subida a ECR"
      - echo "✅ Artefactos generados para CodeDeploy"
      - echo "🎉 Pipeline de CI/CD completado exitosamente"

artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json
    - taskdef.json
    - appspec.yaml
  name: popcorn-ecs-deployment-artifact
